name: Daily Web Scrap

on:
  schedule:
    - cron: "1 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:
    inputs:
      scraper:
        description: "Choose which scraper to run"
        required: true
        default: "both"
        options:
          - "url"
          - "details"
          - "both"

jobs:
  fetch-job-details:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Job URL Scraper
        if: ${{ github.event_name == 'schedule' || github.event.inputs.scraper == 'url' || github.event.inputs.scraper == 'both' }}
        run: python script.py

      - name: Commit and Push Job URLs
        if: ${{ github.event_name == 'schedule' || github.event.inputs.scraper == 'url' || github.event.inputs.scraper == 'both' }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Check if job_post_url.txt has changes
          if ! git diff --quiet job_post_url.txt; then
            git add job_post_url.txt
            git commit -m "Auto-update job_post_url.txt"
            git push origin main
          fi

      - name: Run Job Details Scraper
        if: ${{ github.event_name == 'schedule' || github.event.inputs.scraper == 'details' || github.event.inputs.scraper == 'both' }}
        run: python job-details-scraper.py

      - name: Commit and Push Job Details
        if: ${{ github.event_name == 'schedule' || github.event.inputs.scraper == 'details' || github.event.inputs.scraper == 'both' }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          if ! git diff --quiet job_summary.json; then
            git add job_summary.json
            git commit -m "Auto-update job_summary.json"
            git push origin main
          fi