name: Daily Web Scrap

on:
  schedule:
    - cron: "1 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual execution

jobs:
  fetch-job-details:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Job URL Scraper
        run: python script.py

      - name: Run Job Details Scraper
        run: python job-details-scraper.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          # Pull latest changes from remote to avoid conflicts
          git pull origin main --rebase

          # Check if job_post_url.txt or job_summary.json has changes
          if ! git diff --quiet job_post_url.txt job_summary.json; then
            git add job_post_url.txt job_summary.json
            git commit -m "Auto-update job_post_url.txt and job_summary.json"
            git push origin main
          fi